### ISSUE TITLE
Special keys aren't working

### ISSUE THREAD

**Issue by 01Asaad** [SilvanKohler/Custom-Automation-Language#1]
Simply, the special keys cause the program to stop. I tried ordinary letters and they worked, but when I get to "press tab" or "press enter" or any key like these the program stops and shows me this
![ffs](https://user-images.githubusercontent.com/65569100/82259305-02254e00-9964-11ea-82ca-48136ad556c3.PNG)

**Comment by 01Asaad** [comment]
@SilvanKohler

**Comment by SilvanKohler** [comment]
I heard of this Issue before. I was very busy lately, but I'm trying to fix that ASAP.
Btw thank you for using CAL.

**Comment by SilvanKohler** [comment]
@01Asaad I found the error! I'm trying to fix it now.

**Comment by SilvanKohler** [comment]
Fixed it in commit 808a96fac5f994bcdddcf1c1c01672e2658b0cb1.
Again thank you for submitting this bug.
